<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <ApplicationIcon>Resources\app_icon.ico</ApplicationIcon>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <BaseOutputPath>build\obj\</BaseOutputPath>
    <OutputPath>build\release\</OutputPath>
    <PublishDir>build\release\</PublishDir>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Resources\app_icon.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="QRCoder" Version="1.7.0" />
    <PackageReference Include="Zeroconf" Version="3.7.16" />
  </ItemGroup>

</Project>